name: Deploy Vue.js App to GitHub Pages

on:
  push:
    branches:
      - main # Déclenche le workflow lorsqu'un push est fait sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Version compatible avec Vue.js

    # Étape 3 : Installer les dépendances et construire le projet
    - name: Install dependencies and build
      run: |
        npm install # Installer les dépendances
        npm run build # Construire le projet (génère le dossier 'dist')

    # Étape 4 : Déployer sur GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Dossier de sortie généré par Vue.js
